### PR TITLE
updating tests

### PR DESCRIPTION
**Pull request by djarecka**
I've updated tests, but many from `test_node_task` and `test_workflow` should be still xfailed.

but one test, that should already run,  is failing. I've been debugging it and it looks like `runnable.results_dict` in `Submitter` is set later than `Workflow.run` is checking it.

### CODE REVIEW

**Comment by mgxd** [comment]
what test is failing?

**Comment by djarecka** [comment]
@mgxd - i answered yesterday from my phone, but not sure where it went, since I don't see it here...

anyway, you can see [travis report](https://travis-ci.org/djarecka/pydra/jobs/539246073), but would expect the same problem on your laptop.

**Comment by djarecka** [comment]
you can see  travis report. it simply doesn't use cache locations to find
results

**Comment by djarecka** [comment]
tests are working now

**Pull request merged**
